100 massa web3 page
massalabs/docs pull request #105
Opened 2023-06-30 13:35 UTC by julienbrs

2023-07-03 12:45 UTC, julienbrs commented
@gregLibert here is the first draft of the dev-doc for massa-web3. For now, I have implemented the "How to get started" section (in `massa-web3.mdx`) and detailed descriptions of wallet API operations (in `wallet.mdx`). Before applying this style to the remaining three sections, I wanted to make sure it fits what you were thinking. Massa-web3 docu-dev page is detailed, while the README of the repo will be simplified by removing almost all code snippets removed, making it similar to the other massa READMEs.

I also wasn't sure if I should include a reference to the GitHub code line for each operation (like this:  `Defined in [src/web3/WalletClient.ts:314](https://github.com/massalabs/massa-web3/blob/41f5634/src/web3/WalletClient.ts#L314)` ). I have included this for the first two operations in `wallet.mdx` so you can see what it looks like.

2023-07-03 12:53 UTC, julienbrs commented
> Can you fix the CI @julienbrs ?

done!

2023-07-03 13:58 UTC, qdrn commented
I think the general structure is ok. If we go in that direction then we should make sure that the documentation is always synced with what is being done in the massa-web3 repo.
Maybe make utility it's own section ?

I have some remarks regarding english but this can be addressed once we have a first version.

Side note: we could use this plugin to generate the TS doc of our libraries.

2023-07-03 15:04 UTC, julienbrs commented
> I think the general structure is ok. If we go in that direction then we should make sure that the documentation is always synced with what is being done in the massa-web3 repo. Maybe make utility its own section ?
> 
> I have some remarks regarding english but this can be addressed once we have a first version.
> 
> Side note: we could use [this plugin](https://www.npmjs.com/package/docusaurus-plugin-typedoc) to generate the TS doc of our libraries.

The utility section seems like a good idea indeed.
Maybe we could create a comprehensive integration test that gathers all the code snippets present in docu-dev, so we can identify any broken example code. There are already some integration tests in the massa-web3 repo, we could adapt them to fit our needs?

2023-07-03 15:18 UTC, julienbrs commented on docs/build/massa-web3/massa-web3.mdx
> +  - Coins/Fees: expressed in BigInt's. Coins/fees do however have a metric system behind them. The smallest unit is 10**-9 Massa. All coins/fees are to be expressed as integers scaled by 10**9 and th
Should be fixed, but I'm not sure if it looks the way you intended it to be.

2023-07-04 13:51 UTC, qdrn commented
> Maybe we could create a comprehensive integration test that gathers all the code snippets present in docu-dev, so we can identify any broken example code. There are already some integration tests in the massa-web3 repo, we could adapt them to fit our needs?

You mean for the CI or as an example for users ? Not sure I understand exactly what you propose.

2023-07-05 09:54 UTC, julienbrs commented
We could put all the code examples that are in the docu-dev in an integration tests that would run in the CI. If the CI breaks we would know that we'll have to update the docu-dev. That kind of CI could for example run once per day.

2023-07-05 10:17 UTC, qdrn commented
> We could put all the code examples that are in the docu-dev in an integration tests that would run in the CI. If the CI breaks we would know that we'll have to update the docu-dev. That kind of CI could for example run once per day.

That would be quite nice indeed!

2023-07-12 10:06 UTC, qdrn requested changes
I've made a first pass on the main page.

2023-07-12 10:06 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +```ts
Can't we shorten a bit this part by using tabs ? You can have a look at what was done here: https://massalabs.github.io/docu-dev/docs/build/networks-faucets or here https://docs.near.org/tools/near-api-js/quick-reference#connect

2023-07-12 10:06 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +### Client exposed APIs
I think this subsection can be either removed or made clearer. 

For instance I think you can remove the list of API and corresponding interfaces and keep only the bullet points.
It should also mention util.

2023-07-13 10:52 UTC, julienbrs commented on docs/build/massa-web3/massa-web3.mdx
> +```ts
Done, but I don't know if i should let the "mainnet" and "labnet" sections, isn't the tab too populated?

2023-07-13 15:48 UTC, qdrn requested changes
We are almost there.

Don't be afraid of all the comment. It's quite a nice work overall !

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/events.mdx
> +
```suggestion
### Fetching
```

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/events.mdx
> +
```suggestion
### Polling
```

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/events.mdx
> +Events could also be polled. The js sdk has two methods for doing this as shown below. In both, a filter, a web3 client and a poll interval which
```suggestion
`massa-web3` provides two methods to poll events. Both methods require a filter, a web3 client and a poll interval.
```

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/events.mdx
> +we can set in order to poll the events needs to be provided:
```suggestion
```

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/events.mdx
> +Alternatively, one could make direct use of callback functions as function arguments which would fire on event data received or generated errors:
```suggestion
Alternatively, one can make direct use of callback functions as function arguments to execute code in response of event data received or generated errors:
```

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/events.mdx
> +The latter could easily be employed in smart contracts where we need to e.g. get the contract address. For example, this contract would emit the address at creation:
I don't think this belong here. At least not in this form. If you read rapidly you will probably not understand that this has no direct link to massa-web3. I suggest we make a subsection about event under the develop section.

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/private-api.mdx
> +Add a given Node IP address from the whitelist.
Shouldn't it be "to the whitelist" ?

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +Smart Contracts Client object enables smart contract deployment, calls and streaming of events.
I see no mention of events in this section.

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +Smart contract operations are accessible under the smartcontracts sub-client which is accessible via the smartContracts() method on the client.
```suggestion
Smart contract operations are accessible under the smart contracts sub-client which is accessible via the `smartContracts()` method on the client.
```

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +Smart contract operations are accessible under the smartcontracts sub-client which is accessible via the smartContracts() method on the client.
Either use `smartContracts` or smart contracts.

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +Once the smart contract WASM is available, it becomes quite straightforward to deploy it with the `deploySmartContract` method. This method
Keep it simple!
```suggestion
The `deploySmartContract` method allows to deploy a smart contract using the WASM binary. This method
```

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +There are cases, however, when one might need to wait for a specific status to be reached. This can be achieved using the 'awaitRequiredOperationStatus'
```suggestion
There are cases, however, when one might need to wait for a specific status to be reached. This can be achieved using the `awaitRequiredOperationStatus`
```

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +Smart contract data can be read via the `readSmartContract` method. It executes a dry run Smart contract call and returns some data regarding
```suggestion
Smart contract data can be read via the `readSmartContract` method. It executes a dry run smart contract call and returns some data regarding 
```

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +its execution such as the changes of in the states that would have happen if the transaction was really executed on chain.
Needs to be rephrased!

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +Depending on the smart contract function implementation, the user is to convert the latter into the expected data type.
```suggestion
Depending on the smart contract function implementation, the retrieved data might need to be converted into the expected data type.
```

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +Depending on the smart contract function implementation, the user is to convert the latter into the expected data type.
Might be worth mentioning utils+link here as well ?

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +Smart contract state-changing operations could be executed via callSmartContract method. It executes a Smart contract call and returns the operation id associated.
```suggestion
State-changing smart contract operations can be executed via the `callSmartContract` method. It executes a smart contract call and returns the operation id associated.
```

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +If no executor is provided, the default wallet account from the provided WalletClient will be used.
Same remark as above.

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +Smart contract data can be read via the `readSmartContract` method. It executes a dry run Smart contract call and returns some data regarding
There's probably a confusion with the `executeReadOnly` method ?

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +### Read a contract with an other contract
See remark for ExecuteReadOnly

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +Get the proto file of the contracts from the Massa Blockchain. It takes an array of contract addresses as parameter and returns the array of
This is something very specific to Massa. We need to give more context! Maybe somewhere else and cross reference.

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/utils.mdx
> +All Massa values that are being used or returned by web3 (gas, fees, coins and rolls) are expressed via BigInt's. Massa-web3 has however a few convenience methods and converters that might come handy
```suggestion
All Massa values that are being used or returned by web3 (gas, fees, coins and rolls) are expressed via BigInt's. Massa-web3 has however a few convenience methods and converters that might come handy. Below is a summary of available methods and some examples of the latter:
```

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/utils.mdx
> +All Massa values that are being used or returned by web3 (gas, fees, coins and rolls) are expressed via BigInt's. Massa-web3 has however a few convenience methods and converters that might come handy
What is "of the latter"? Probably say it explicitly.

2023-07-13 15:48 UTC, qdrn commented on docs/build/massa-web3/wallet.mdx
> +Get {secretKey, publicKey} for all accounts in the wallet.
Should be rephrased.

2023-07-20 11:14 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +const opId: string = await web3Client.smartContracts().deploySmartContract(
I think there is a `maxCoins` parameter as well now.

2023-07-20 11:14 UTC, qdrn commented on docs/build/massa-web3/smart-contracts.mdx
> +const opId: string = await web3Client.smartContracts().deploySmartContract(
It may apply elsewhere as well!

2023-07-24 14:01 UTC, julienbrs commented
I'm moving this branch + PR to `on-hold` and will open a new one with the new direction decided for the massa-web3 docudev. Will close this branch when we will be 100% sure that nothing here would be useful

2023-07-25 08:08 UTC, closed without merging