create guidelines to create a plugin
massalabs/docs pull request #118
Opened 2023-07-12 15:18 UTC by Pierregvx

2023-07-12 16:12 UTC, qdrn commented
Can you use .mdx files instead of .md if we want to add html later ?

2023-07-12 21:07 UTC, Pierregvx commented
> Can you use .mdx files instead of .md if we want to add html later ?

Done 👍

2023-07-13 08:11 UTC, Thykof requested changes

2023-07-17 08:16 UTC, thomas-senechal requested changes
Nice beginning ! 

I think there are a lot of rephrasing to do, and some parts are missing.
For example, you are not talking about the fact that plugins are basically binaries with a few specifities, that are defined in this file:
- To be installed in MS, the plugin must be released as Zip Archives for each targetted OS. For now MS handles:
    - Win 10/11, AMD64
    - Linux, AMD64
    - MacOS, AMD64
    - MacOS, ARM64
    Maybe we should add a link to a doc of MS that specifies the supported OSs to avoid updating multiple parts of the doc when we will support other targets (do not spend too much time on this, it's details)
- The plugin root directory must contain a `manifest.json`, logo...
- At start up, the plugin receives an ID as parameter
- The plugin must register as a MassaStation plugin using `plugin-manager/register` endpoint with the ID

After explaining that MS plugins are basically binaries, we need to redirect people to the "create plugin"

We should not talk about a specific language. Yes, we use Go everywhere and we will focus on using Go in some of our docs (such as "create plugin"), but this part only defines plugins specifications, so it shouldn't focus on a specific language. Having a plugin system that is language agnostic is a stength of MS plugins and so, we should show it.

2023-07-17 08:16 UTC, thomas-senechal commented on docs/build/plugin/guidelines.mdx
> +| Version     | Module version                | semver | XX.XX.XX          |
I understand what is "semver" because I know it, but it's not an http format. So in my opinion, we should change it as: 
```suggestion
| Version     | Module version                | text | Using [Semantic Versioning 2.0](https://semver.org/spec/v2.0.0) |
```

Please check that it is possible to render links in a table like. Otherwise, we can move the link to a comment under the table

2023-07-17 08:16 UTC, thomas-senechal commented on docs/build/plugin/guidelines.mdx
> +> ```
I think I heard that it is possible to import code from URLs, could we use the `Manifest.json` from the hello world plugin directly? So we could visualize it here and add a link to it if people wants to see it "in action".

2023-07-17 08:16 UTC, thomas-senechal commented on docs/build/plugin/guidelines.mdx
> +- **Operation ID:** `pluginManagerRegister`
I think those are useless since we are explaining it before and the OperationID is specific to the Go Code inside MassaStation

2023-07-17 08:16 UTC, thomas-senechal commented on docs/build/plugin/guidelines.mdx
> +To be compatible with Massa Station, the plugin artifact must contain the following files :
I don't really undestand why you are talking about "artifact" here. I guess you are talking about the archive, for example that we store in the Github Releases

```suggestion
## Artifact requirements

To be compatible with Massa Station, the plugin zip archive must contain the following files :
```

2023-07-17 09:12 UTC, Pierregvx commented on docs/build/plugin/guidelines.mdx
> +Your plugin will need to call **the Register Endpoint** to be compatible with Massa Station: The plugin should be able to call the `register` endpoint in Massastation defined [here](https://github.co
change applied

2023-07-17 09:21 UTC, Pierregvx commented on docs/build/plugin/guidelines.mdx
> +| Logo        | Module logo file name         | text   | 40px x 40px max   |
I'll remove the image size - this constraint is only for the store.
I gave the constraints [here](https://github.com/massalabs/docu-dev/blob/ed8665b37e1224e44b1381712594d60ec5153b3a/docs/build/plugin/guidelines.mdx#L46-L47) do you think I should mention it again ?

2023-07-17 09:23 UTC, Pierregvx commented on docs/build/plugin/guidelines.mdx
> +| Logo        | Module logo file name         | text   | 40px x 40px max   |
it works

2023-07-17 12:10 UTC, Thykof commented on docs/build/plugin/introduction.mdx
> +For that, the Station app provides a module store with all existing plug-and-play services. As a user, you simply have to download Massa Station (link to the landing page) and start customizing your
add "link to the landing page"

2023-07-17 12:13 UTC, Thykof commented on docs/build/plugin/guidelines.mdx
> +Your plugin will need to call **the Register Endpoint** to be compatible with Massa Station: The plugin should be able to call the `/plugin-manager/register` endpoint of Massastation, as defined in [
```suggestion
Your plugin will need to call **the Register Endpoint** to be compatible with Massa Station: The plugin should be able to call the `/plugin-manager/register` endpoint of Massastation, as defined in [MassaStation Swagger File](https://github.com/massalabs/station/blob/main/api/swagger/server/restapi/resource/swagger.yml#L481).
```

2023-07-17 12:14 UTC, Thykof commented on docs/build/plugin/guidelines.mdx
> +    - `url` (string, required): URL authority to use for connecting to the plugin.
we should apply DRY (don't repeat yourself) the source of truth is on the link to the swagger file just above

2023-07-17 12:15 UTC, Thykof commented on docs/build/plugin/guidelines.mdx
> +There must be a plugin logo in the artifact. it must be a [valid image file](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types)
word artifact is not accurate. We talk about artifact of a github action job. We talk about assets of a release. we provide to the plugin manager a zip archive.

```suggestion
There must be a plugin logo in the zip archive. it must be a [valid image file](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types)
```

2023-07-17 12:17 UTC, Thykof commented on docs/build/plugin/guidelines.mdx
> +The manifest will provide the necessary information to the Massa Station to display the plugin in the UI. It must be a `manifest.json` file at the root of the artifact. It must contain the following
```suggestion
The manifest will provide the necessary information to the Massa Station to display the plugin in the UI. It must be a `manifest.json` file at the root of the artifact. It must contain the following properties:
```

2023-07-17 14:30 UTC, Thykof commented on docs/build/plugin/guidelines.mdx
> +Your plugin will need to call **the Register Endpoint** to be compatible with Massa Station: The plugin should be able to call the `/plugin-manager/register` endpoint of Massastation, as defined in [
you are right, then we should put this link: https://github.com/massalabs/station/blob/v0.2.5/api/swagger/server/restapi/resource/swagger.yml#L481

with the tag and the line, this can't change.

2023-07-17 14:33 UTC, thomas-senechal commented on docs/build/plugin/guidelines.mdx
> +Your plugin will need to call **the Register Endpoint** to be compatible with Massa Station: The plugin should be able to call the `/plugin-manager/register` endpoint of Massastation, as defined in [
But that means we will need to update it when we do a new version
Otherwise we redirect people to an older version of the spec

2023-07-17 14:48 UTC, Thykof commented on docs/build/plugin/guidelines.mdx
> +Your plugin will need to call **the Register Endpoint** to be compatible with Massa Station: The plugin should be able to call the `/plugin-manager/register` endpoint of Massastation, as defined in [
true but the question is: what is worse between redirect to incorrect line in the file or old spec?

2023-07-21 07:28 UTC, Pierregvx commented on docs/build/plugin/guidelines.mdx
> +> ```
I just tried to do that. It works in a readme file but not here. I can continue to try to find something

2023-07-21 07:45 UTC, Thykof commented on docs/build/plugin/guidelines.mdx
> +You can developp a plugin in any wanted language. The easiest way is to use go with the the [plugin hello-world](https://github.com/massalabs/station-massa-hello-world) hook to register the plugin.
I think we need the link to https://github.com/massalabs/station-massa-hello-world anywhere in this doc.

2023-07-21 08:23 UTC, AurelienFT reviewed
I found it very understandable !

2023-07-21 09:27 UTC, thomas-senechal commented on docs/build/plugin/guidelines.mdx
> +Your plugin will need to call **the Register Endpoint** to be compatible with Massa Station: The plugin should be able to call the `/plugin-manager/register` endpoint of Massastation, as defined in [
I guess we just need to make sure that if we modify the endpoint, we reflect the changes in this doc (and so, update the URL)

2023-07-21 09:32 UTC, Pierregvx commented on docs/build/plugin/guidelines.mdx
> +Your plugin will need to call **the Register Endpoint** to be compatible with Massa Station: The plugin should be able to call the `/plugin-manager/register` endpoint of Massastation, as defined in [
sounds good, I'll use it

2023-07-21 13:24 UTC, Thykof reviewed
I only read, not tested the rendering of the website.

2023-07-21 13:24 UTC, Thykof commented on docs/build/plugin/guidelines.mdx
> +To be compatible with Massa Station, the plugin zip archive must contain the following files :
```suggestion
To be compatible with Massa Station, the plugin zip archive must contain the following files:
```

2023-07-21 13:24 UTC, Thykof commented on docs/build/plugin/guidelines.mdx
> +The manifest will provide the necessary information to the Massa Station to display the plugin in the UI. It must be a `manifest.json` file at the root of the artifact. It must contain the following
```suggestion
The manifest will provide the necessary information to the Massa Station to display the plugin in the UI. It must be a `manifest.json` file at the root of the zip archive. It must contain the following properties:
```

2023-07-21 13:24 UTC, Thykof commented on docs/build/plugin/guidelines.mdx
> +> ```
I think it's ok, you can add bellow:

"See the manifest of the Hello-World plugin as an example: https://github.com/massalabs/station-massa-hello-world/blob/v0.0.8/manifest.json"

2023-07-24 07:15 UTC, Thykof requested changes

2023-07-24 07:15 UTC, Thykof commented on docs/build/plugin/guidelines.mdx
> +To be installed in Massa Station, a plugin must be packaged" as a Zip Archive, tailored for each targeted operating system.
```suggestion
To be installed in Massa Station, a plugin must be packaged as a Zip Archive, tailored for each targeted operating system.
```

2023-07-24 07:15 UTC, Thykof commented on docs/build/plugin/guidelines.mdx
> +-->
todo here, I would do it now or open an issue to not lost the idea.

2023-07-24 08:17 UTC, Pierregvx commented on docs/build/plugin/guidelines.mdx
> +-->
issue for massastation doc: https://github.com/massalabs/docu-dev/issues/129

2023-07-24 08:46 UTC, Thykof approved these changes

2023-07-26 07:44 UTC, thomas-senechal approved these changes

2023-07-26 07:47 UTC, Thykof commented
@qdrn this PR is ready for our side, can you review and merge if everything is okay?

2023-07-27 08:32 UTC, qdrn commented on docs/build/plugin/introduction.mdx
> +For that, the Station app provides a module store with all existing plug-and-play services. As a user, you simply have to [download Massa Station](https://github.com/massalabs/station/releases) and s
What does `for that` refer to ?

2023-07-27 08:32 UTC, qdrn commented on docs/build/plugin/introduction.mdx
> +For that, the Station app provides a module store with all existing plug-and-play services. As a user, you simply have to [download Massa Station](https://github.com/massalabs/station/releases) and s
I'd rather have the link refer to the entry point of Massa Station (station.massa.net).

2023-07-27 08:51 UTC, qdrn commented on docs/build/plugin/introduction.mdx
> +## Technically, what is a plugin ?
Do we need a section for a one-liner ?

2023-07-27 08:52 UTC, qdrn commented on docs/build/plugin/introduction.mdx
> +:::tip
The first time you mention plugins you can say something like `plugins, or modules, ...` and then remove this tip. It doesn't add much imo.

2023-07-27 08:55 UTC, qdrn commented on docs/build/plugin/guidelines.mdx
> +When Massa Station starts a plugin, it generates a unique ID for the plugin and passes it as a parameter to the plugin binary. Once the plugin is started, it must register itself on Massa Station to
```suggestion
When Massa Station starts a plugin, it generates a unique ID for the plugin and passes it as a parameter to the plugin binary. Once the plugin has started, it must register itself to Massa Station to confirm that it is running properly.
```
Feel free to rephrase a bit.

2023-07-27 09:30 UTC, Pierregvx commented on docs/build/plugin/introduction.mdx
> +For that, the Station app provides a module store with all existing plug-and-play services. As a user, you simply have to [download Massa Station](https://github.com/massalabs/station/releases) and s
I can replace it with `To avail of these benefits`

2023-07-27 09:46 UTC, Pierregvx commented on docs/build/plugin/introduction.mdx
> +:::tip
WDYT @thomas-senechal  ?

2023-07-27 12:41 UTC, qdrn reviewed
I've made a few suggestions. Let me know what you think.

I believe that sentences like this: "These guidelines ensure that the plugin integrates smoothly with Massa Station, allowing users to easily leverage its features and benefits." are too vague and provide little added value to users, especially on an intro page. Maybe on the `guidelines` page.

2023-07-27 12:41 UTC, qdrn commented on docs/build/plugin/introduction.mdx
> +To avail of these benefits, the Station app provides a module store with all existing plug-and-play services. As a user, you simply have to run Massa Station, access [the entry point](station.massa.n
I believe we could keep only the last sentence (without the "entrepreneur" imo) and build around it.

2023-07-27 12:41 UTC, qdrn commented on docs/build/plugin/introduction.mdx
> +To avail of these benefits, the Station app provides a module store with all existing plug-and-play services. As a user, you simply have to run Massa Station, access [the entry point](https://station
```suggestion
```

2023-07-27 12:41 UTC, qdrn commented on docs/build/plugin/introduction.mdx
> +At its core, a plugin is a binary that adheres to specific guidelines defined [here](./guidelines). These guidelines ensure that the plugin integrates smoothly with Massa Station, allowing users to e
```suggestion
As a developer, you can easily build your own module, and add it to the store to make it accessible to all Massa Station users. At its core, a plugin is a binary that adheres to specific [guidelines](./guidelines).
```

2023-07-27 12:44 UTC, thomas-senechal commented on docs/build/plugin/introduction.mdx
> +:::tip
That's a good idea but I'm scared that people think that those are 2 different things

2023-07-27 12:50 UTC, thomas-senechal commented on docs/build/plugin/introduction.mdx
> +For that, the Station app provides a module store with all existing plug-and-play services. As a user, you simply have to [download Massa Station](https://github.com/massalabs/station/releases) and s
I didn't know this website already existed
That's a good idea to use it yes !

2023-07-27 16:11 UTC, qdrn requested changes
Almost ready!

2023-07-27 16:11 UTC, qdrn commented on docs/build/plugin/introduction.mdx
> +:::tip
So I suggest we remove it and if we see it's confusing we'll add a note.

2023-07-27 21:57 UTC, qdrn approved these changes

2023-07-27 22:03 UTC, merged