add how to create a plugin
massalabs/docs pull request #121
Opened 2023-07-13 10:19 UTC by Pierregvx

2023-07-13 16:01 UTC, qdrn commented on docs/build/plugin/createplugin.mdx
> +# Creating a plugin : step by step
```suggestion
# Creating a plugin: step by step
```

2023-07-13 16:01 UTC, qdrn commented on docs/build/plugin/createplugin.mdx
> +> Here we have defined two endpoints :
```suggestion
> Here we have defined two endpoints:
```

2023-07-13 16:01 UTC, qdrn commented on docs/build/plugin/createplugin.mdx
> +- add the following code to it :
```suggestion
- add the following code to it:
```

2023-07-13 16:02 UTC, qdrn commented on docs/build/plugin/createplugin.mdx
> +- Finally we need to add the handler to the `initializeAPI` function :
```suggestion
- Finally we need to add the handler to the `initializeAPI` function:
```

2023-07-13 16:02 UTC, qdrn commented on docs/build/plugin/createplugin.mdx
> +> you should see the following output :
```suggestion
> you should see the following output:
```

2023-07-13 16:02 UTC, qdrn commented on docs/build/plugin/createplugin.mdx
> +- set up the cors : the cors will allow the plugin to be called from the massastation server
```suggestion
- set up the cors: the cors will allow the plugin to be called from the massastation server
```

2023-07-13 16:03 UTC, qdrn commented on docs/build/plugin/createplugin.mdx
> +- create a `generate.go` file : `touch generate.go`
```suggestion
- create a `generate.go` file: `touch generate.go`
```

2023-07-13 16:03 UTC, qdrn commented on docs/build/plugin/createplugin.mdx
> +> - `/api/hello` : the endpoint that will greet the user
```suggestion
> - `/api/hello`: the endpoint that will greet the user
```

2023-07-13 16:03 UTC, qdrn commented on docs/build/plugin/createplugin.mdx
> +  - Initialize it with the different endpoints you want to expose, for example :
```suggestion
  - Initialize it with the different endpoints you want to expose, for example:
```

2023-07-13 16:03 UTC, qdrn commented on docs/build/plugin/createplugin.mdx
> +  - create a file named `swagger.yml` : `touch api/swagger.yml`
```suggestion
  - create a file named `swagger.yml`: `touch api/swagger.yml`
```

2023-07-16 20:21 UTC, AurelienFT commented
Can you provide some explanations on why me review is valuable here please ? So that I can organize myself if it's really needed to not block anything here.

2023-07-17 07:37 UTC, SlnPons commented
> Can you provide some explanations on why me review is valuable here please ? So that I can organize myself if it's really needed to not block anything here.

Yes, of course. @AurelienFT you've been pinged because you tried to create a plugin already and this step by step is supposed to give you all the details you need to achieve it. 
So I thought that you could take 10-15 min to read quickly and let us know if: 
* it's clear enough? 
* you get the info you would have liked to read?
* eventually missing points?

Only if you have time of course, thanks a lot 🙏

2023-07-17 10:10 UTC, thomas-senechal requested changes
Good job ! 

I think we still have some changes to do to make it ready for the Mainnet and ensure that it's clear for everybody.

Also, I think that this tutorials relies too much on "copy pasting". I think we need to explain more what the code does. 

Maybe a way to make it easier to read and understand would be to divide it in multiple parts, for example:
- Part 1, basic plugin, gets the ID from args, registers, print "Hello world" each second
- Part 2, add basic API, add swagger, an endpoint like helloworld `/api/hello` https://github.com/massalabs/station-massa-hello-world/blob/efad9a86b737bd5e56bffb9d96cdea3b45335ca7/api/swagger.yml#L40
- Part 3, add a basic front end

Our goal isn't to explain how Swagger works exactly, so we don't need to add more endpoints. We just want to make sure people understand how to make a plugin, that a plugin might be, only a front end plugin, or only an API, or both...

2023-07-17 10:10 UTC, thomas-senechal commented on docs/build/plugin/createplugin.mdx
> +#### Create a web app
Not sure we can call it a "web app". I think we should rename it "Add a front end" or something like that

2023-07-21 07:52 UTC, Pierregvx commented on docs/build/plugin/createplugin.mdx
> +mkdir station-massa-hello-world && cd station-massa-hello-world
Not sure I get this, should I just put: 
 create a folder `station-massa-hello-world` and navigate to it ?

2023-07-21 07:56 UTC, Pierregvx commented on docs/build/plugin/createplugin.mdx
> +- Run `task install`
I think that using task is practical to avoid having to change the doc if we change some commands

The template sounds like a good idea. I could use the one I did while writing the doc

2023-07-21 08:27 UTC, AurelienFT commented on docs/build/plugin/createplugin.mdx
> +- Create the folders `web/content` and add `hello_world.svg` in it.
There is already this file on the folder it's unclear to me if we use the existing template or not at this point.

2023-07-21 08:29 UTC, AurelienFT commented on docs/build/plugin/createplugin.mdx
> +
Maybe link to the documentation of openAPI to understand fully this file and know how to edit it

2023-07-21 08:30 UTC, AurelienFT commented on docs/build/plugin/createplugin.mdx
> +    "github.com/my-username/station-massa-hello-world/api/server/restapi/operations"
I don't understand why there is `my-username` here. If it's normal an explanation is needed somewhere

2023-07-21 08:33 UTC, AurelienFT commented on docs/build/plugin/createplugin.mdx
> +- In the `main` function, initialize the API and start the server.
Maybe mention that we need to create the main function. (if it's an other file than station-massa-hello-world.go mentioning it could be nice)

2023-07-21 08:34 UTC, AurelienFT commented on docs/build/plugin/createplugin.mdx
> +- You should see the following output:
which output ?

2023-07-21 08:34 UTC, AurelienFT commented on docs/build/plugin/createplugin.mdx
> +- Add the right endpoint to the `swagger.yml` file.
Would be nice to mention full path api/server

2023-07-21 09:04 UTC, Pierregvx commented on docs/build/plugin/createplugin.mdx
> +    "github.com/my-username/station-massa-hello-world/api/server/restapi/operations"
this would be the github user name, should I specify it or remove it ? 
I initialised the go project with it [here](https://github.com/massalabs/docu-dev/blob/9ea8fbc9bf0cb43fb4772378628e95177af28b42/docs/build/plugin/createplugin.mdx#L24-L25)

2023-07-21 09:55 UTC, Pierregvx commented on docs/build/plugin/createplugin.mdx
> +- You should see the following output:
removed :+1:

2023-07-21 13:34 UTC, Pierregvx commented on docs/build/plugin/createplugin.mdx
> +#### Create a web app
done

2023-07-21 13:35 UTC, Pierregvx commented on docs/build/plugin/createplugin.mdx
> +
added a todo in comment

2023-07-21 13:39 UTC, Pierregvx commented on docs/build/plugin/createplugin.mdx
> +- Create the folders `web/content` and add `hello_world.svg` in it.
I added a line to specify that we are building the plugin from scratch to clarify

2023-07-21 15:04 UTC, AurelienFT commented on docs/build/plugin/createplugin.mdx
> +    "github.com/my-username/station-massa-hello-world/api/server/restapi/operations"
Currently, it's unclear that we have to replace and if I replace how it will fetch on the github as I didn't push anything yet. This is unclear to me

2023-07-24 09:58 UTC, AurelienFT reviewed
Didn't tested it but I understand the tutorial, nothing is wired to me.

2023-07-27 16:04 UTC, qdrn commented on docs/tutorial/massa-station-plugin/Introduction.mdx
> +This tutorial will show you how to create a simple plugin using Go and Swagger. It is possible to use other languages and frameworks such as explained in the [plugin guidelines](../../build/plugin/gu
Can you use absolute links ? I think it's needed for the CI anyway.

2023-07-27 20:30 UTC, Pierregvx commented
I splited this pr between 
https://github.com/massalabs/docs/pull/164
https://github.com/massalabs/docs/pull/166
https://github.com/massalabs/docs/pull/167
https://github.com/massalabs/docs/pull/168

2023-07-27 20:30 UTC, closed without merging

2023-07-27 20:31 UTC, Pierregvx commented on docs/tutorial/massa-station-plugin/Introduction.mdx
> +This tutorial will show you how to create a simple plugin using Go and Swagger. It is possible to use other languages and frameworks such as explained in the [plugin guidelines](../../build/plugin/gu
corrected in https://github.com/massalabs/docs/pull/164