116 fetch wallet end to end tests
massalabs/docs pull request #122
Opened 2023-07-13 13:59 UTC by julienbrs

closes #116

2023-07-19 08:11 UTC, gregLibert requested changes

2023-07-19 08:11 UTC, gregLibert commented on .github/workflows/fetch-code.yml
> +      - name: Fetch end-to-end test from other repo
I think it's better to clone the project instead. do ing this will allow to generate code, build and test the project before using the code. it will act as a security belt.

2023-07-19 08:11 UTC, gregLibert commented on .github/workflows/fetch-code.yml
> +      - name: Commit Changes
Do you need everything ? Don't you think that we should chose what function we want here ? maybe using a script shell

2023-07-19 08:11 UTC, gregLibert commented
@julienbrs can you clarify which file is created manually here ?

2023-07-19 08:29 UTC, julienbrs commented
> @julienbrs can you clarify which file is created manually here ?

Everything in code-fetched/wallet has been generated, the rest has been coded manually for this PR (`fetch-code.yml` and `extract-test-code.ts`).

2023-07-19 08:34 UTC, julienbrs commented on .github/workflows/fetch-code.yml
> +      - name: Commit Changes
I'm not sure that I understand what you ask, I'm generated the components code for every function of the `wallet` operations subclient API because all these functions will appear in docu-dev with their own code example

2023-07-19 11:46 UTC, julienbrs commented on .github/workflows/fetch-code.yml
> +      - name: Fetch end-to-end test from other repo
Should be good

2023-07-21 07:48 UTC, gregLibert commented
@julienbrs @Ben-Rey I think we should sync on this.

2023-07-25 08:09 UTC, julienbrs commented
According to our discussion on our needs for tests and docudev, I'm closing this PR. I'll delete that branch after being 100% sure that we don't need that code fetching logic anymore

2023-07-25 08:10 UTC, julienbrs commented
According to our discussion on our needs for tests and docudev, I'm closing this PR. I'll delete that branch after being 100% sure that we don't need that code fetching logic anymore

2023-07-25 08:10 UTC, closed without merging