documentate how to use swagger for api calls
massalabs/docs pull request #126
Opened 2023-07-18 12:43 UTC by B-Naoufal

2023-07-18 12:48 UTC, Thykof reviewed
how do we access to that document? from a readme? from the menu of docu-dev?

2023-07-18 12:57 UTC, B-Naoufal commented
> how do we access to that document? from a readme? from the menu of docu-dev?

@Thykof from the menu , there is already a dedicated space for massa station

2023-07-18 14:29 UTC, thomas-senechal requested changes
IMO, we could make it even simpler by removing mention of MassaStation, redirect people to the Official Postman Documentation, and then tell people to change the `{{baseUrl}}` to `station.massa`. 

Note that if we remove the mentions to MassaStation and perform the changes I suggested on Step 4, it won't work for plugins since we will still need to update the `{{baseUrl}}` with the right URL for the plugin (if running using MassaStation)
Unless we can put the base URL in the swagger file of the plugin such as `https://station.massa/plugin/{author}/{plugin}/` 🤔

2023-07-18 14:29 UTC, thomas-senechal commented on docs/build/wallet/swagger_with_postman.md
> +# Using Postman with Swagger
This file is supposed to be a `.mdx`

2023-07-18 14:29 UTC, thomas-senechal commented on docs/build/wallet/massa-station.mdx
> +To use the MassaStation endpoints in Postman, import the API specifications Swagger file by following the steps outlined in the [Postman Import document](swagger_with_postman.md).
Are you sure you can do links like that ? 
Please test it

2023-07-18 14:29 UTC, thomas-senechal commented on docs/build/wallet/swagger_with_postman.md
> +This guide provides a high-level overview of using Postman with Swagger to interact with an API. Follow these 5 steps to get started:
There are only 4 steps

```suggestion
This guide provides a high-level overview of using Postman with Swagger to interact with an API. Follow these 4 steps to get started:
```

2023-07-18 14:29 UTC, thomas-senechal commented on docs/build/wallet/swagger_with_postman.md
> +3. **Ensure MassaStation is Running**: Start your MassaStation by using the command `task build-run`.
Only works if the user as cloned MassaStation repository and starts it from sources
What if I installed it using the installer and doesn't want to build it from sources ?

2023-07-18 14:46 UTC, B-Naoufal commented on docs/build/wallet/massa-station.mdx
> +To use the MassaStation endpoints in Postman, import the API specifications Swagger file by following the steps outlined in the [Postman Import document](swagger_with_postman.md).
yes in mdx you can specify the relative path to the file you want to link to.

2023-07-18 14:54 UTC, thomas-senechal commented on docs/build/wallet/massa-station.mdx
> +To use the MassaStation endpoints in Postman, import the API specifications Swagger file by following the steps outlined in the [Postman Import document](swagger_with_postman.md).
Sorry, my comment lacks of context, I wasn't talking about Markdown, nor `mdx`, I was talking about in this project
AFAIK, it's not how it's supposed to be done in this project https://github.com/massalabs/docu-dev/blob/34b59ea9c6cc9c9f152d7b2e5f2d0301dd1a8bab/docs/learn/architecture/node-architecture.mdx#L10

2023-07-18 15:05 UTC, B-Naoufal commented on docs/build/wallet/swagger_with_postman.md
> +1. **Locate the Swagger File**: Find the `swagger.yml` [file](https://github.com/massalabs/thyra/blob/e25eef54d5901ea16dddd7258ee09481a3e794a0/api/swagger/server/restapi/resource/swagger.yml) for the
it would be much easier if there is a direct doc from postman for our specific use case , unfortunately it's not the case, that's why i spend time adding this doc. only doc i found from postman : https://learning.postman.com/docs/designing-and-developing-your-api/importing-an-api/

2023-07-19 06:32 UTC, thomas-senechal commented on docs/build/wallet/swagger_with_postman.md
> +4. **Interact with an Endpoint**: Expand the imported API in Postman and select the desired endpoint (e.g., "all Domains Getter"). Replace `{{baseUrl}}` with `station.massa` by clicking on the "..."
Not here for sure, but we could try it to see if we can simplify the doc

2023-07-19 06:38 UTC, thomas-senechal commented on docs/build/wallet/swagger_with_postman.md
> +4. **Interact with an Endpoint**: Expand the imported API in Postman and select the desired endpoint (e.g., "all Domains Getter"). Replace `{{baseUrl}}` with `station.massa` by clicking on the "..."
https://learning.postman.com/docs/api-governance/api-definition/openapi2/#resolution-11 
Maybe with `host` ?

2023-07-19 06:39 UTC, thomas-senechal commented on docs/build/wallet/swagger_with_postman.md
> +1. **Locate the Swagger File**: Find the `swagger.yml` [file](https://github.com/massalabs/thyra/blob/e25eef54d5901ea16dddd7258ee09481a3e794a0/api/swagger/server/restapi/resource/swagger.yml) for the
What about this link ?
https://learning.postman.com/docs/integrations/available-integrations/working-with-openAPI/
It talks about OpenAPI, but "Swagger" was "OpenAPI" name before version 3.0, and it's still compatible even if not showed in [available-integrations](https://learning.postman.com/docs/integrations/available-integrations/apimatic/)

2023-07-19 09:54 UTC, thomas-senechal approved these changes

2023-07-20 10:07 UTC, qdrn commented
Thanks for the work. However I think there are multiple issues at different levels with this PR:
- we don't have any documentation on Massa Station and so this documentation will lack a lot of context for users: what's this swagger for, what do you use this API for, massa plugins ? what are massa plugins ? etc...
- this specific document is mostly about how to use Postman in the end. I totally agree with @thomas-senechal that it's not our job to explain how to use Postman and that we can probably link to a tutorial made by Postman or someone else. We don't have the manpower to explain how to use tools made by other companies. Unless that's absolutely a critical component that a lot of people will use and that's badly documented we should avoid that at all cost.
- the documentation organisation is not good. This very technical developer documentation does not belong under the wallet section.

2023-07-20 10:08 UTC, qdrn requested changes
For now I would put this on hold until we have a documentation on massa station.

2023-08-14 14:43 UTC, B-Naoufal commented
> For now I would put this on hold until we have a documentation on massa station

@longgamma-massa check here !

2024-01-09 16:16 UTC, Thykof commented
postman UI is now very straightforward to do this. I think we should consider closing this PR.

2024-01-09 16:18 UTC, closed without merging