Improve deployement part
massalabs/docs pull request #149
Opened 2023-07-26 05:53 UTC by Ben-Rey

2023-07-26 06:27 UTC, AurelienFT reviewed
Can you also add the usage of is deploying contract in the contract example?

2023-07-26 07:28 UTC, julienbrs approved these changes

2023-07-26 07:28 UTC, julienbrs commented on docs/build/quickstart.mdx
> +  :::
```suggestion
:::
```

2023-07-26 07:28 UTC, julienbrs commented on docs/build/quickstart.mdx
> +  :::
```suggestion
:::
```

2023-07-26 07:37 UTC, AurelienFT approved these changes

2023-07-26 07:59 UTC, qdrn requested changes

2023-07-26 07:59 UTC, qdrn commented on docs/build/quickstart.mdx
> +After deployment, the event will be displayed in the console. This event contains the address of your deployed smart contract and the event message set in the constructor function.
Which event ? It is never mentioned before so it feels a bit weird. I suggest making it a bit more clear in the `Writing and Deploying the Smart Contract` section. Something simple.

2023-07-26 20:53 UTC, Ben-Rey commented on docs/build/quickstart.mdx
> +After deployment, the event will be displayed in the console. This event contains the address of your deployed smart contract and the event message set in the constructor function.
I just changed "the" to "an". I try to add it in  Writing and Deploying the Smart Contract but it was repetitive.

2023-07-27 07:19 UTC, qdrn approved these changes

2023-07-27 07:19 UTC, merged