Create-a-plugin-intro-and-set-up
massalabs/docs pull request #164
Opened 2023-07-27 14:37 UTC by Pierregvx

2023-07-31 09:43 UTC, Thykof approved these changes

2023-07-31 09:49 UTC, Thykof commented
I you don't ask to install goswagger, it will fail at the next part when running go generate

2023-07-31 09:52 UTC, Pierregvx commented
> I you don't ask to install goswagger, it will fail at the next part when running go generate

thanks for the catch ! I'll add it

2023-08-01 11:15 UTC, Thykof requested changes

2023-08-01 11:15 UTC, Thykof commented on docs/tutorial/massa-station-plugin/set-up-plugin.mdx
> +First, create and navigate to the folder `my-plugin` and then start your module using:
```suggestion
First, create and navigate to the folder `my-plugin` and then initialize your project using:
```

2023-08-01 11:16 UTC, Thykof approved these changes
my suggestion above is no blocking

2023-08-22 17:23 UTC, closed without merging