178 massa web3 page
massalabs/docs pull request #182
Opened 2023-08-01 13:29 UTC by julienbrs

closes #178

2023-08-01 18:52 UTC, Ben-Rey commented
Just for info, we will put an example for poll events but we need first to add an example that use it. @julienbrs if you can confirm or correct me.

2023-08-02 08:01 UTC, jcbaillie commented
Small issue: I don't seem to be able to "npm run build" it:

```
[ERROR] Unable to build website for locale en.
[ERROR] Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path th
at does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and le
t the build pass.

Exhaustive list of all broken links found:

- On source page path = /docs/build/massa-web3/dapp-usage-massa-web3:
   -> linking to /docs/usage-massa-web3#args (resolved as: /docs/usage-massa-web3)

    at throwError (C:\Dev\massa-quickstart\docs\node_modules\@docusaurus\logger\lib\index.js:76:11)
    at handleBrokenLinks (C:\Dev\massa-quickstart\docs\node_modules\@docusaurus\core\lib\server\brok
enLinks.js:153:47)
    at async buildLocale (C:\Dev\massa-quickstart\docs\node_modules\@docusaurus\core\lib\commands\bu
ild.js:186:5)
    at async tryToBuildLocale (C:\Dev\massa-quickstart\docs\node_modules\@docusaurus\core\lib\comman
ds\build.js:41:20)
    at async mapAsyncSequential (C:\Dev\massa-quickstart\docs\node_modules\@docusaurus\utils\lib\jsU
tils.js:34:24)
    at async Command.build (C:\Dev\massa-quickstart\docs\node_modules\@docusaurus\core\lib\commands\
build.js:76:21)
```

2023-08-02 08:24 UTC, jcbaillie commented on docs/build/massa-web3/backend-usage-massa-web3.mdx
> +You can find also find the full typescript documentation [here](https://web3.docs.massa.net/classes/WalletClient.html).
"find also find" => "also find"

2023-08-02 12:38 UTC, julienbrs commented
> Small issue: I don't seem to be able to "npm run build" it:
> 
> ```
> [ERROR] Unable to build website for locale en.
> [ERROR] Error: Docusaurus found broken links!
> 
> Please check the pages of your site in the list below, and make sure you don't reference any path th
> at does not exist.
> Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and le
> t the build pass.
> 
> Exhaustive list of all broken links found:
> 
> - On source page path = /docs/build/massa-web3/dapp-usage-massa-web3:
>    -> linking to /docs/usage-massa-web3#args (resolved as: /docs/usage-massa-web3)
> 
>     at throwError (C:\Dev\massa-quickstart\docs\node_modules\@docusaurus\logger\lib\index.js:76:11)
>     at handleBrokenLinks (C:\Dev\massa-quickstart\docs\node_modules\@docusaurus\core\lib\server\brok
> enLinks.js:153:47)
>     at async buildLocale (C:\Dev\massa-quickstart\docs\node_modules\@docusaurus\core\lib\commands\bu
> ild.js:186:5)
>     at async tryToBuildLocale (C:\Dev\massa-quickstart\docs\node_modules\@docusaurus\core\lib\comman
> ds\build.js:41:20)
>     at async mapAsyncSequential (C:\Dev\massa-quickstart\docs\node_modules\@docusaurus\utils\lib\jsU
> tils.js:34:24)
>     at async Command.build (C:\Dev\massa-quickstart\docs\node_modules\@docusaurus\core\lib\commands\
> build.js:76:21)
> ```

my bad, thanks for the review!

2023-08-02 12:47 UTC, jcbaillie commented on docs/build/massa-web3/massa-web3.mdx
> +  .getAccountBalance("address);
typo

2023-08-02 13:01 UTC, jcbaillie commented
The text is clear and examples are good. I did not test the code snippets because I don't have all the pieces (like massa station, which cannot install on my WSL-equipped Windows for now). If this is not done yet (there were typos, so probably it was not done yet), I would recommend having somebody naïvely copy/pasting all code extracts in "noobs" conditions (fresh install everything from scratch, no magic trick) and run them to make sure it works. In my experience, it always fails on some small detail at some point, and then all the devs reading the doc will fall on it too and flood the support :)

2023-08-04 13:57 UTC, qdrn requested changes
I've made a couple of suggestions.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +You can either initialize a client with the help of the Wallet-provider or without it.
Add link for Wallet-provider.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +You can either initialize a client with the help of the Wallet-provider or without it.
We need to populate the wallet-provider page btw.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +You can either initialize a client with the help of the Wallet-provider or without it.
I would provide a bit more context. Something like:
"Some usage of massa-web3 require an account. This account can be either provided using Wallet-provider or directly in the code".

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +secret keys and other sensitive information. The Wallet-provider will automatically search for a wallet plugin installed
```suggestion
secret keys and other sensitive information. The Wallet-provider will automatically detect if a wallet is installed and connect to it.
```
I would remove plugin as it's not necessarily a plugin.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +and connect to it.
```suggestion
```

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +        "Please install massa station and the wallet plugin of Massa Labs and refresh."
```suggestion
        "Please install massa station and the wallet plugin and refresh."
```

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  deployerPrivateKey
Why deployerPrivateKey ? And not simply privateKey ?

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  baseAccount // optional parameter, will be used as default account when no account is specified
When no account is provided then it's not baseAccount that is used as it does not exist to begin with ? I'm confused about the comment.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  deployerPrivateKey
Same as above.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  baseAccount // optional parameter, will be used as default account when no account is specified
Same as above.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  deployerPrivateKey
Same.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  baseAccount // optional parameter, will be used as default account when no account is specified
Same.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  deployerPrivateKey
Same.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  baseAccount // optional parameter, will be used as default account when no account is specified
Same.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  deployerPrivateKey
Same.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  baseAccount // optional parameter, will be used as default account when no account is specified
Same.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  deployerPrivateKey
Same.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  baseAccount // optional parameter, will be used as default account when no account is specified
Same.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +Please note that specifying a base account is only optional at this point, a client can be initialized without it if you
```suggestion
Please note that specifying a base account is only optional at this point. An account is needed only to perform operations that require a signature.
```

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +don't need to sign transactions. You can learn more about how to manage the base account in the [Wallet Operations](https://web3.docs.massa.net/classes/WalletClient.html) section.
```suggestion
You can learn more about how to manage the base account in the [Wallet Operations](https://web3.docs.massa.net/classes/WalletClient.html) section.
```

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/backend-usage-massa-web3.mdx
> +you will need to write your secret key directly in your code. Initialization of the client is shown in the [introduction](/docs/build/massa-web3#without-wallet-provider)
Is it really how you would do it ? It would probably be passed as an environment variable or something more complex (not expert). I think it gives a wrong impression.

I might be wrong.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/backend-usage-massa-web3.mdx
> +Methods available such as creating or importing an account, getting account information, sending transactions, signing
I don't understand the context ? What do you want to say here ?

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/backend-usage-massa-web3.mdx
> +All the node operations are available through the private API, typescript documentation can be found [here](https://web3.docs.massa.net/classes/PrivateApiClient.html).
```suggestion
All the operations needed to manage a node are available through the private API. The corresponding Typescript documentation can be found [here](https://web3.docs.massa.net/classes/PrivateApiClient.html).
```

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/backend-usage-massa-web3.mdx
> +Getting information about the blockchain can be done through the public API, typescript documentation can be found
```suggestion
Reading the state of the blockchain can be done through the public API. The corresponding Typescript documentation can be found
```

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/dapp-usage-massa-web3.mdx
> +After creating a react app with `npx create-react-app helloworld` and setting up the Massa Web3 API as described in the
I don't think it's worth mentioning how to create a react project.

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/dapp-usage-massa-web3.mdx
> +We want our frontend to call the smart contract and change the age value associated to Alice.
```suggestion
This snippets shows how to call the smart contract and change the age value of Alice.
```

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/dapp-usage-massa-web3.mdx
> +Here is the [age smart contract](https://github.com/massalabs/massa-sc-examples/blob/main/age/contracts/assembly/contracts/main.ts).
```suggestion
The [age smart contract](https://github.com/massalabs/massa-sc-examples/blob/main/age/contracts/assembly/contracts/main.ts) stores the name and age of persons.
```

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/dapp-usage-massa-web3.mdx
> +It allows you to store and read an age value for a given person name.
```suggestion
```

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/dapp-usage-massa-web3.mdx
> +We now want to read the new age value we just set to display it in our frontend. You can directly read smart contract datastore values
```suggestion
You can directly read smart contract datastore values
```

2023-08-04 13:57 UTC, qdrn commented on docs/build/massa-web3/dapp-usage-massa-web3.mdx
> +Since the `getAge` method won't change the state of the smart contract, we don't need to use a client with an account linked to it.
```suggestion
Since the `getAge` method doesn't change the state of the smart contract, we don't need to use a client with an account linked to it.
```

2023-08-11 16:57 UTC, qdrn commented
There are still a few unresolved comments @julienbrs.

2023-08-14 12:09 UTC, julienbrs commented on docs/build/massa-web3/massa-web3.mdx
> +  baseAccount // optional parameter, will be used as default account when no account is specified
When we init a client with a baseAccount, we don't need to specify account for the upcoming calls as baseAccount will be used by default as the executor. However, you can also init a client without baseAccount, but you will then have to always specify who will be the executor of the calls
The comment is indeed not very clear, is it better now?

2023-08-21 07:02 UTC, qdrn commented on docs/build/massa-web3/backend-usage-massa-web3.mdx
> +If you need to interact with the Massa network for your backend, you can use the Massa Web3 API without the wallet provider. Therefore
```suggestion
If you need to interact with the Massa network for your backend, you can use the Massa Web3 API without the wallet provider.
```

2023-08-21 07:02 UTC, qdrn commented on docs/build/massa-web3/backend-usage-massa-web3.mdx
> +you will need to pass the secret keys as environment variables. Initialization of the client is shown in the [introduction](/docs/build/massa-web3#without-wallet-provider)
```suggestion
Initialization of the client is shown in the [introduction](/docs/build/massa-web3#without-wallet-provider)
```

2023-08-21 07:02 UTC, qdrn approved these changes

2023-08-21 07:44 UTC, qdrn commented on docs/build/massa-web3/massa-web3.mdx
> +  baseAccount // optional parameter, will be used as default account when no account is specified
Yes, thanks!

2023-08-21 07:45 UTC, merged