Hello world plugin
massalabs/docs pull request #200
Opened 2023-08-23 19:12 UTC by leoloco

I have drafted all the necessary steps for the tutorial to implement the hello-world MS plugins. 
It is still missing a lot of context and explanation, but I wish to get reviewed upon the "logic" of the tutorial. 
Feel free to elaborate your comments as I'm not so familiar with go, and I might have missed some important points.

2023-08-24 12:41 UTC, Thykof requested changes
This is my partial review

2023-08-24 14:16 UTC, leoloco commented on docs/build/hello-world-plugin-1.mdx
> +Make sure you have [Go Swagger](https://pkg.go.dev/github.com/go-swagger/go-swagger) installed on your machine. If you don't have Go Swagger installed, you can follow the [official installation guide
The procedure in the link I provided is to run `go get` while the installation link you provided suggests otherwise. Don't you think we should recommend user to use the `go get` installation ?

2023-08-24 14:25 UTC, Thykof commented on docs/build/hello-world-plugin-1.mdx
> +Make sure you have [Go Swagger](https://pkg.go.dev/github.com/go-swagger/go-swagger) installed on your machine. If you don't have Go Swagger installed, you can follow the [official installation guide
yes, developers needs to install the binary and the lib, I'm afraid go get will only install the lib

2023-08-24 14:32 UTC, leoloco commented on docs/build/hello-world-plugin-1.mdx
> +}
Could you please provide a suggestion?

2023-08-24 14:56 UTC, Thykof commented on docs/build/hello-world-plugin-1.mdx
> +}
I'll try but the tuto needs to explain to replace the content of the setupGlobalMiddleware function in my-plugin/api/server/restapi/configure_my_plugin.go

2023-08-24 14:57 UTC, leoloco commented on docs/build/hello-world-plugin-1.mdx
> +So go ahead and create the file `endpoints.go` in the `my-plugin/api` folder.
Well, I agree with you but that's how the folder is named in this repo https://github.com/massalabs/station-massa-hello-world
I prefer to keep it this way until main repo is updated.

2023-08-24 14:57 UTC, Thykof commented on docs/build/hello-world-plugin-1.mdx
> +}
```suggestion
```

2023-08-24 15:01 UTC, leoloco commented on docs/build/hello-world-plugin-1.mdx
> +Make sure you have [Go Swagger](https://pkg.go.dev/github.com/go-swagger/go-swagger) installed on your machine. If you don't have Go Swagger installed, you can follow the [official installation guide
It seems like go get installs both as I only followed this method of installation and ended up having swagger CLI available in my terminal

2023-08-24 15:05 UTC, Thykof commented on docs/build/hello-world-plugin-1.mdx
> +Make sure you have [Go Swagger](https://pkg.go.dev/github.com/go-swagger/go-swagger) installed on your machine. If you don't have Go Swagger installed, you can follow the [official installation guide
sounds good then, but I know people experienced multiple issues about this. We do go get in our contributing files so yes let's do this.

2023-08-25 10:25 UTC, qdrn reviewed
I've read a large portion. Thanks for the good work.

One general comment is that I believe that the large introduction at the start could belong to it's own section. It would ease the reading I believe.

Side comment: didn't we agree to put things regarding Massa Station in it's own sidebar section ?

2023-08-25 10:25 UTC, qdrn commented on docs/build/hello-world-plugin-1.mdx
> +To be able to register the plugin with Massa Station, we need to install the Massa Station Plugin package. Indeed, this package contains the `RegisterPlugin` function that allows us to register the p
It's outside the scope but it's a bit weird that you need to install a "Hello world" package to create a "Hello world" plugin ? I think it's rather misnamed.

2023-08-25 10:28 UTC, Thykof commented on docs/build/hello-world-plugin-1.mdx
> +To be able to register the plugin with Massa Station, we need to install the Massa Station Plugin package. Indeed, this package contains the `RegisterPlugin` function that allows us to register the p
yes, related to https://github.com/massalabs/station/issues/612#issuecomment-1692039120

2023-09-11 09:34 UTC, qdrn commented
FYI we made a whole Massa Station section in https://github.com/massalabs/docs/pull/205. I think you will need to refactor a bit.

2023-10-02 14:44 UTC, qdrn approved these changes

2023-10-02 14:44 UTC, qdrn commented on docs/massaStation/hello-world-plugin.mdx
> +## What are Massa Station and Massa Station plugins?
To rebalance! @leoloco

2023-10-06 15:32 UTC, leoloco commented
@qdrn I think this can be merged

2023-10-09 15:39 UTC, merged