Remove station GUI installation
massalabs/docs pull request #240
Opened 2023-11-28 10:09 UTC by thomas-senechal

2023-11-28 12:06 UTC, SlnPons commented on docs/massaStation/install.mdx
>  2. Open your file manager and navigate to the location where the `.deb` package is saved.
Step 5 below (sorry I don't why I can't comment directly on it) needs to have the link updated to use: ### Updating on Linux

2023-11-29 09:01 UTC, thomas-senechal commented on docs/massaStation/install.mdx
>  2. Open your file manager and navigate to the location where the `.deb` package is saved.
Fixed !

2024-01-09 16:19 UTC, Thykof approved these changes

2024-01-09 16:58 UTC, qdrn requested changes

2024-01-09 16:58 UTC, qdrn commented on docs/massaStation/install.mdx
> +If you experience any issues during an update, please refer to the [FAQ](/docs/massaStation/faq).
```suggestion
If you experience any issues during the update, please refer to the [FAQ](/docs/massaStation/faq).
```

2024-01-09 16:58 UTC, qdrn commented on docs/massaStation/install.mdx
> +There is a known issue involving version checks while updating _Massa Station_ via the GUI, follow these instructions for best results:
```suggestion
There is a known issue involving version checks while updating _Massa Station_ via the GUI. To avoid this issue we recommend following these instructions:
```

2024-01-09 16:58 UTC, qdrn commented on docs/massaStation/install.mdx
> +There is a known issue involving version checks while updating _Massa Station_ via the GUI, follow these instructions for best results:
Don't we want to recommend these instructions directly if there is a known issue with the other method ?

2024-01-10 08:53 UTC, Thykof commented on docs/massaStation/install.mdx
> +There is a known issue involving version checks while updating _Massa Station_ via the GUI, follow these instructions for best results:
cc @thomas-senechal

2024-01-10 09:05 UTC, qdrn approved these changes

2024-04-10 08:21 UTC, qdrn commented
Should this be unblocked or just closed ? cc @thomas-senechal

2024-04-23 15:43 UTC, thomas-senechal commented
> Should this be unblocked or just closed ? cc @thomas-senechal

I think we can merge it if you agree with [my comment](https://github.com/massalabs/docs/pull/240#discussion_r1576485039)

2024-04-23 16:52 UTC, Thykof commented on docs/massaStation/install.mdx
> +:::info Important
sounds more like french
```suggestion
:::Important informations
```

2024-04-23 19:37 UTC, qdrn commented on docs/massaStation/install.mdx
> +:::info Important
There is no s to information (https://english.stackexchange.com/questions/117552/why-does-information-not-have-a-plural-form).

2024-04-24 08:35 UTC, qdrn commented on docs/massaStation/install.mdx
> +:::info Important
This was edited by NS hence the confusion

2024-04-24 08:43 UTC, thomas-senechal commented on docs/massaStation/install.mdx
> +:::info Important
Following last commit, it's broken: 
<img width="888" alt="image" src="https://github.com/massalabs/docs/assets/44696378/389f56f9-c022-40f1-83c7-ca40469025e3">

2024-04-24 09:36 UTC, merged