28 general structure
massalabs/docs pull request #29
Opened 2023-05-13 22:13 UTC by qdrn

2023-05-13 22:13 UTC, qdrn commented
This PR is **not** meant to be merged but should be viewed as a meta PR for future work.

2023-05-15 08:06 UTC, gregLibert commented on docs/build/api copy.mdx
to be renamed to sdk.mdx

2023-05-15 08:08 UTC, gregLibert commented on docs/build/frontend.mdx
> +TODO: explain how to interact with a smart contract using a frontend through massa-web3 library.
I think we should focus on wallet-provider instead.

2023-05-15 08:10 UTC, gregLibert commented on docs/build/wallets.mdx
> +- Bearby
even if it's incompatible with wallet-provider  and therefor unusable for a dapp?

2023-05-15 09:08 UTC, gregLibert requested changes

2023-05-15 09:08 UTC, gregLibert commented on docs/learn/architecture.mdx
Mostly what is existing here: https://docs.massa.net/en/latest/general-doc/architecture.html

2023-05-15 09:08 UTC, gregLibert commented on docs/learn/autonomous-sc.mdx
improve significantly: https://docs.massa.net/en/latest/general-doc/autonomous-sc.html

2023-05-15 09:08 UTC, gregLibert commented on docs/learn/decentralized-web.mdx
Improve significantly https://docs.massa.net/en/latest/general-doc/decentralized-web.html

2023-05-15 09:08 UTC, gregLibert commented on sidebars.js
> +      value: "<span class='menu__link'><b><small> Developer Tools </small></b></span>"
faucet page is missing. Should include a description of the build net and the testnet

2023-05-15 09:08 UTC, gregLibert commented on docs/tutorial/home.mdx
We should focus first on two examples with a detailed walkthrough:
- one simple
- one advanced

and then link massa examples

2023-05-15 10:58 UTC, qdrn commented on docs/build/frontend.mdx
> +TODO: explain how to interact with a smart contract using a frontend through massa-web3 library.
One thing that is still not clear for me is how wallet-provider will be used. Will people be only using wallet-provider in the front end and it will call wallets that are using massa-web3 (or something else) to implement SC calls etc... ?

2023-05-15 12:38 UTC, qdrn commented on sidebars.js
> +  buildSidebar: [
I've made a new proposal. Let me know what you think of it!

2023-05-15 12:41 UTC, qdrn commented on sidebars.js
> +      value: "<span class='menu__link'><b><small> Developer Tools </small></b></span>"
Added a `networks & faucets` section.

2023-05-15 12:48 UTC, gregLibert commented on docs/build/frontend.mdx
> +TODO: explain how to interact with a smart contract using a frontend through massa-web3 library.
People can:
- use the wallet provider for classic operations (covered by the wallet standard)
- use massa-web3 initialized with a wallet-provider for more advanced operations (all operations doable by massa-web3)

This way, a Dapp only needs to focus on wallet provider implementation and a new wallet only needs to focus on the content script part of the wallet provider.

2023-05-15 12:54 UTC, gregLibert commented on sidebars.js
> +      value: "<span class='menu__link'><b><small> Developer Tools </small></b></span>"
cool!

2023-05-15 12:54 UTC, gregLibert commented on sidebars.js
> +  buildSidebar: [
I don't see it in the build part. I only saw thr plugin wallet.

2023-05-15 12:55 UTC, gregLibert requested changes

2023-05-15 12:55 UTC, gregLibert commented on sidebars.js
> +      value: "<span class='menu__link'><b><small> Developer Tools </small></b></span>"
should also add ercXXX standard (and maybe others)

2023-05-15 13:17 UTC, qdrn commented on sidebars.js
> +  buildSidebar: [
Sorry I messed up. Should be good now!

2023-05-15 13:21 UTC, qdrn commented on sidebars.js
> +      value: "<span class='menu__link'><b><small> Developer Tools </small></b></span>"
I made a proposal. Let me know!

2023-05-15 14:29 UTC, gregLibert approved these changes

2023-06-20 11:51 UTC, SlnPons commented on docs/build/wallet/massa-station.mdx
> +title: Massa Station
Not sure to understand why Massa Station is in the wallet part. 
The way it is built (however we may want to present and market it differently & i don't mind at all) is that: 
Massa Station is a plugin manager Device-app and one of its plug-in: Massa Wallet is a wallet.

2023-07-25 14:20 UTC, closed without merging

2023-07-25 14:29 UTC, qdrn commented
I've closed since most of the structure has been implemented and it starts not being relevant anymore.