299 create bridge documentation
massalabs/docs pull request #302
Opened 2024-04-09 21:10 UTC by leoloco

2024-04-10 08:11 UTC, longgamma-massa commented on docs/massaBridge/home.mdx
> +For more details, please refer to the Massa Bridge FAQ: [https://bridge.massa.net/](https://bridge.massa.net/).
Add link to FAQ: https://bridge.massa.net/faq

2024-04-10 08:14 UTC, longgamma-massa commented on docs/massaBridge/instructions.mdx
> +   - For Massa Station Wallet (recommended): Ensure the Massa Station desktop app is installed, open, and running. For Massa Station-related questions, please refer to [Massa Station FAQ](https://doc
```suggestion
   - For Massa Station Wallet (recommended): Ensure the Massa Station desktop app is installed, open, and running. For Massa Station-related questions, please refer to [Massa Station FAQ](https://docs.massa.net/docs/massaStation/faq) and [Massa Wallet Instructions](https://docs.massa.net/docs/massaStation/massa-wallet/getting-started).
```suggestion
   - For Massa Station Wallet (recommended): Ensure the Massa Station desktop app is installed, open, and running. For Massa Station-related questions, please refer to [Massa Station FAQ](https://docs.massa.net/docs/massaStation/faq) and [Massa Wallet FAQ](https://docs.massa.net/docs/massaStation/massa-wallet/getting-started).
```
```

2024-04-10 08:17 UTC, longgamma-massa commented on docs/massaBridge/instructions.mdx
> +Note: You will need to sign up to 2 transactions on Ethereum, and none on Massa.
```suggestion
Note: You will need to sign up to 2 transactions on Ethereum, and none on Massa.
```
:::note
You will need to sign up to 2 transactions on Ethereum, and none on Massa. 
:::

2024-04-10 08:17 UTC, longgamma-massa commented on docs/massaBridge/instructions.mdx
> +Note: You will need to sign up to 3 transactions: 2 on Massa, and 1 on Ethereum network.
```suggestion
Note: You will need to sign up to 3 transactions: 2 on Massa, and 1 on Ethereum network.
```
:::note
You will need to sign up to 3 transactions: 2 on Massa, and 1 on Ethereum network.
:::

2024-04-10 10:11 UTC, longgamma-massa requested changes
@leoloco for the preference of writing: I prefer yours over gpt. 
Left a few comments and suggestions

2024-04-10 10:11 UTC, longgamma-massa commented on docs/massaBridge/architecture-security.mdx
> +The bridgeVault contract on Ethereum holds the assets locked during the bridging process. The only way assets can be redeemed is by sending a message signed by the 3 out of 3 nodes of the relayer net
you address this contract as 'BridgeVault' in the above content, so let's use the same naming below as well for clarity.

2024-04-10 10:11 UTC, longgamma-massa commented on docs/massaBridge/architecture-security.mdx
> +![Off chain architecture](off-chain-architecture.png)
I wonder if sharing this info in so much detail is smart. For example: to a normal user who wants to ensure himself the bridge is secure, knowing that we use: EC2, lambda, amplify etc doesn't mean much. For someone wanting to exploit Bridge, it is valuable info (correct me if I am wrong). If you agree, I suggest that we simplify this scheme by mentioning vaguely backend architecture without these specifics.

2024-04-10 10:11 UTC, longgamma-massa commented on docs/massaBridge/architecture-security.mdx
> +The bridgeVault contract on Ethereum holds the assets locked during the bridging process. The only way assets can be redeemed is by sending a message signed by the 3 out of 3 nodes of the relayer net
OpenZeppelin instead openzeppelin

2024-04-10 12:23 UTC, leoloco commented on docs/massaBridge/architecture-security.mdx
> +
From certik audit page 16: `A medium/blog link for sharing the timelock contract and multi-signers addresses information with the public audience.`

2024-04-10 12:51 UTC, leoloco commented on docs/massaBridge/architecture-security.mdx
> +![Off chain architecture](off-chain-architecture.png)
Okay, so the previous diagram is sufficient, let's just delete this diagram.

2024-04-10 13:03 UTC, leoloco commented on docs/massaBridge/architecture-security.mdx
> +![Off chain architecture](off-chain-architecture.png)
FYI, reverse engineering our relayer network would be a matter of minutes for any serious hacker. Obfuscating our architecture won't impact our security. But being too vague might not be reassuring for legit users

2024-04-11 12:56 UTC, longgamma-massa commented
@peterjah can you review architecture and security page?

2024-04-12 19:09 UTC, longgamma-massa commented
@SlnPons check overall documentation  
@gregLibert can you review Architecture and Security page so that Leo has a reviewer?

2024-04-15 06:38 UTC, gregLibert requested changes

2024-04-15 06:38 UTC, gregLibert commented on docs/massaBridge/architecture-security.mdx
> +| SRE         | 0xPqr7890...StuV1234                      | Inactive |
Why is it inactive ?

2024-04-15 06:38 UTC, gregLibert commented on docs/massaBridge/architecture-security.mdx
> +Safe proxy address: [0x5d752840501b2d2f4841accf53794d0ed3e2c3eb](https://sepolia.etherscan.io/address/0x5d752840501b2d2f4841accf53794d0ed3e2c3eb)
What is it on buildnet?

2024-04-15 06:38 UTC, gregLibert commented on docs/massaBridge/architecture-security.mdx
> +The Massa Bridge smart contracts have undergone security audits conducted by Certik, the report is publicly available [here](https://drive.google.com/file/d/1onla7nqsow26RZYXfJE2ju0vGwdjfttA/view?usp
Certifk doesn't provide a public link?

2024-04-15 06:38 UTC, gregLibert commented on docs/massaBridge/home.mdx
> +| Massa | DAI.e | _add token contract link_ |
to be updated?

2024-04-15 06:38 UTC, gregLibert commented on docs/massaBridge/architecture-security.mdx
> +The Massa Bridge smart contracts have undergone security audits conducted by Certik, the report is publicly available [here](https://drive.google.com/file/d/1onla7nqsow26RZYXfJE2ju0vGwdjfttA/view?usp
Publishing is in progress.

2024-04-15 08:09 UTC, leoloco commented on docs/massaBridge/home.mdx
> +| Massa | DAI.e | _add token contract link_ |
yes indeed

2024-04-15 08:49 UTC, gregLibert approved these changes

2024-04-15 09:48 UTC, gregLibert approved these changes

2024-04-15 12:41 UTC, longgamma-massa approved these changes

2024-04-15 13:02 UTC, merged